# Lesson 01: Numpy Exercises

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## 1. Numpy array creation basics (I)

1. Write a python list of integer numbers, then create a 1-d numpy array out of it. Read out the
element type from the array. (There is a specific array attribute for that, make sure that you know
what it is! The mnemonic to remember what it is is "data type".)

2. Then do the same for a list of floating point numbers.  Again, read out the element type.

3. Then create a list in which there is a mix of integers and floating point numbers, e.g. `[1, 2.0, 3]`, and create a numpy array from it.  What do you expect to happen in such case?  Verify your
expectations by checking in practice.

4. What if you wanted to ensure that the element type is floating point even when your input list only
contains integers?

5. What happens if your starting list contains floating point values but you try to force it to a
`bool` element type?

6. What happens if your list has elements which are not numbers, e.g. if some elements are strings?
Check this. Inspect your results carefully. Get an element of the array out (e.g. with `a[0]`) and
then check its type with the `type` built-in function. Is the result an instance of a string? Check
it with `isinstance`.

7. What about if one or more elements are sets, or dicts?

In [6]:
# 1.

# Write a python list of integer numbers, then create a 1-d numpy array out of it. Read out the
# element type from the array. (There is a specific array attribute for that, make sure that you know
# what it is! The mnemonic to remember what it is is "data type".)
import numpy as np
l = [1, 2, 3, 4, 5]
a = np.array(l)
print(a.dtype)


int64


## 2. Numpy array creation basics (II)

1. Create a 2x3 array of zeros. Print the shape.

2. Create a 3x3x4 array of ones. 

3. Create a 2x2  array of random standard Gaussian numbers

4. Write a function that takes a single argument `n` and creates a 1-d array of size `n`, filled with
the value `-1` (integer). Do it in a single line of code. Exploit the simplest of the broadcasting
rules. **Note:** there are at least 3 ways to do this. Can you figure them all out?


In [27]:
import numpy as np
def array1(n): return np.zeros(n) -1 
def array2(n): return np.full(n, -1)
def array3(n): return np.array([-1 for i in range(n)])
print( array1(5), array2(5), array3(5))

[-1. -1. -1. -1. -1.] [-1 -1 -1 -1 -1] [-1 -1 -1 -1 -1]


## 3. Reading out array chunks

1. Write a function that takes a list as its argument, let's say that it is of length n . The function
should first create a 1-d array from this list. Then, it should read out the first half of the array.
Then it should read out the second half. Both these operations must be performed with one line
of code each. If n is odd, then the middle element should be put in the second list.

2. If you were working with Python lists, you could concatenate back the two halves using + . With
numpy arrays you can't do that though. Why? (Try it; use both lists with even and odd n , and see
what happens.)

3. Look up the function np.hstack in the numpy documentation (maybe also look at np.stack
and np.vstack while you're at it, although they are not necessary for this exercise). Using that
function, you should be able to concatenate the two halves and get back an array like the original
one. Do that, and return the result.m

In [65]:
def arraychunks(a): 
    b = np.array(a)
    return np.split(b,[int(len(b)/2)])
b = arraychunks([1,2,3,4,5])
print(b, np.hstack((b[0], b[1])))



[array([1, 2]), array([3, 4, 5])] [1 2 3 4 5]


## 4. Slicing in strides

Write a function that takes a list as its argument, let's say it is of length `n`. Let's also
assume that `n>0` for simplicity (the input list is not empty). The function should first create a
1-d array from this list. Then, it should read out all the elements with even indices, in a new
array. Then all the elements with odd indices. Both these operations must be performed with one
line of code each, using slicing expressions.

In [87]:
def evenorodd(a):
    b = np.array(a)
    return  np.array([ b[i] for i in range(len(a)) if i%2==0]), np.array([ b[i] for i in range(len(a)) if i%2!=0])
evenorodd([1,2,3,4,5,6,7])


(array([1, 3, 5, 7]), array([2, 4, 6]))

## 5. Indexing with lists

Write a function that takes a list as its argument, let's say it is of length `n`. Let's also say
for simplicity that `n` is odd and that `n>=1`. As for the previous exercises, the function should
create a 1-d array from this list.  Use an indexing expression that uses another list (of length 3)
to extract a new array which contains, the first, the middle and the last element of the original
array. (Since `n` is odd, the array will always have a middle element.) For example, if your input
list is `[4,6,1,2,0,7,9]`, then your result should contain `4`, `2` and `9`.

Do you get a view or not from this? Write some code that verifies your answer.

**Important note:** If `n==1`, the 3 elements of your indexing list should be the same: this is no
problem at all! When you use a list for indexing, there can be repetitions in the list. The result
will just be an array with 3 identical values. To convince yourself, try to index an array with
different lists and observe what happens, and observe what happens in particular if you have
repetitions, e.g. take an array of length 3 and observe that you can use a list like `[2, 0, 1, 0,
0, 1]`, resulting in an output array of length 6: larger than the original!

In [94]:
def middle(a):
    b = np.array(a)
    return np.array([b[0], b[int(len(a)/2)], b[len(a)-1]])
middle([2,0,1,0,0,1])

array([2, 0, 1])

## 6. Indexing with masks

Write a function that takes a list as its argument, let's say it is of length `n`. Let's also say
that the list may contain both positive and negative numbers. As for the previous exercises, the
function should create a 1-d array from this list. Compare the whole array with `0`, i.e. do
something like `a > 0`. What is the result? Check this.

Use the result as a mask in an indexing expression. You want to get a new array which contains only
the elements of the original array that are non-negative. For example, if your input list is `[3,
-1, -2, 5, 6, -3, 8]`, your output should contain `3`, `5`, `6` and `8`. Can you do this with a
single indexing expression? (Yes you can!)

Do you get a view or not from this? Write some code that verifies your answer.

In [106]:
def maskindexing(a): 
    b = np.array(a)
    return np.array( [b[i] for i in range(len(a)) if b[i]> 0]) 
maskindexing([1,2, -7, 3,-4, 7])



array([1, 2, 3, 7])

## 7. Sums

- Generate a 3x4 array of random normal numbers
- Using the `sum` method, compute the total sum of the elements
- Using the `sum` method, compute the total sum of the elements along the columns. The result should be an array with 4 elements
- Using the `sum` method, compute the total sum of the elements along the rows. The result should be an array with 3 elements

## 8. reshape and stack

- Use `np.arange` to create an array with 12 elements
- reshape it to a 3x4 array and call `x` the result. You should notice that numpy arrays are row-major
- Create a new array that can be stacked with `x` along the first dimension
- Create a new array that can be stacked with `x` along the second dimension


In [142]:
#Sums
rand_n= np.random.randn(3,4)
print
(   
    rand_n, 
    np.sum(rand_n), #sum of all values
    np.sum(rand_n, axis= 0), #sum of columns (row axis is set to 0)
    np.sum(rand_n, axis= 1) #sum of rows (row axis is ste to 1)
)

#Reshape and stack
x = np.arange(12).reshape((3,4))
print(
    x, 
    np.vstack((x,rand_n)), 
    np.hstack((x, rand_n))
    )


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0.          1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.         10.         11.        ]
 [-1.56287531  0.51318161 -0.5970855   1.5310655 ]
 [ 1.01721465  0.19904103 -1.26119948 -0.07318979]
 [-1.50093332  1.53696632  0.66062235  1.65584605]] [[ 0.          1.          2.          3.         -1.56287531  0.51318161
  -0.5970855   1.5310655 ]
 [ 4.          5.          6.          7.          1.01721465  0.19904103
  -1.26119948 -0.07318979]
 [ 8.          9.         10.         11.         -1.50093332  1.53696632
   0.66062235  1.65584605]]


## 9. Broadcast

- Create an 3x4 array `x` of gaussian numbers
- compute the element-wise exponential of `x`
- sum `x` to a 1d array `y` of 4 numbers. Do you understand what kind of broadcasting is involved
- sum `x` to an array `y` of 3 numbers. `y` should be created or reshaped to a suitable shape for broadcasting with `x`

In [155]:
x = np.random.randn(3,4)
exp_x= np.exp(x)
y = np.arange(4)
y_new = np.arange(3).reshape((3,1))
print(x, y_new, x + y_new) #x+y sums all element of y to every row of x if number of elements coincide (same for columns)

[[ 0.85504191 -0.53289906 -0.36808167  0.45786232]
 [-0.45944739 -1.44611125  0.53435701 -1.96030436]
 [ 1.22089112 -1.68824787 -1.12193753  0.22282651]] [[0]
 [1]
 [2]] [[ 0.85504191 -0.53289906 -0.36808167  0.45786232]
 [ 0.54055261 -0.44611125  1.53435701 -0.96030436]
 [ 3.22089112  0.31175213  0.87806247  2.22282651]]
